/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ShirtModel.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useSnapshot } from "valtio";
import { useFrame } from '@react-three/fiber';
import { Decal, useTexture } from '@react-three/drei';

import state from "../store";

export function ShirtModel(props) {
  const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF("/shirt/ShirtModel.gltf");

  const logoTexture = useTexture(snap.logoDecal);


  const stateString = JSON.stringify(snap);

  return (
    <group {...props} dispose={null} key={stateString}>
      <mesh
        geometry={nodes.T_Shirt_male.geometry}
        material={materials.lambert1}
      >
        {snap.isLogoTexture && (
          <Decal
            position={[0, 0.04, 0.15]}
            rotation={[0, 0, 0]}
            scale={0.15}
            map={logoTexture}
            anisotropy={16}
            depthTest={false}
            depthWrite={true}
          />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload("/ShirtModel.gltf");
